import{a as b,S as w,i as n}from"./assets/vendor-mdVVRe9K.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const L="46037450-a04b7b74a12a46e49ae394c24",R="https://pixabay.com/api/",g=15;async function p(s,r=1){const a=new URLSearchParams({key:L,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:g}),t=`${R}?${a}`;try{const{data:{hits:e,totalHits:o,total:i}}=await b.get(t);return{hits:e,totalHits:o,total:i}}catch(e){throw console.error(e),new Error}}function f(s,r){const a=s.map(t=>`
    <a href="${t.largeImageURL}" class="gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
      <ul class="info">
        <li><p>Likes</p> ${t.likes}</li>
        <li><p>Views</p> ${t.views}</li>
        <li><p>Comments</p> ${t.comments}</li>
        <li><p>Downloads</p> ${t.downloads}</li>
      </ul>
    </a>`).join("");r.insertAdjacentHTML("beforeend",a)}const S=document.querySelector(".search-form-js"),l=document.querySelector(".gallery-js"),y=document.querySelector(".load-more"),d=document.querySelector(".loading-indicator");let h=new w(".gallery-item",{captionsData:"alt",captionDelay:250}),c="",m=1,u=0;S.addEventListener("submit",q);y.addEventListener("click",P);async function q(s){s.preventDefault();const r=s.currentTarget;if(c=r.elements.query.value,c===""){n.error({title:"No Results",message:"Please enter a search query.",position:"topRight"});return}m=1,l.innerHTML="",y.style.display="none",d.style.display="block";try{const{hits:a,totalHits:t}=await p(c,m);u=t,f(a,l),h.refresh(),a.length>0&&u>g?y.style.display="block":u===0&&n.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}catch(a){console.log(a),n.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{d.style.display="none",r.reset()}}async function P(){d.style.display="block",m++;try{const{hits:s}=await p(c,m);f(s,l),h.refresh();const{height:r}=l.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"}),l.querySelectorAll(".gallery-item").length>=u&&(y.style.display="none",n.info({title:"Information",message:"We're sorry, but you've reached the end of search results."}))}catch(s){console.log(s),n.error({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{d.style.display="none"}}
//# sourceMappingURL=index.js.map
